# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-11 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gastoAlimento', models.FloatField(default=0)),
                ('gastoTransporte', models.FloatField(default=0)),
                ('aumentoAlimento', models.FloatField(default=0)),
                ('aumentoTransporte', models.FloatField(default=0)),
            ],
        ),
    ]
