# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-12 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflaciometro', '0003_auto_20161211_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datausuario',
            name='aumentoAlimentos',
        ),
        migrations.RemoveField(
            model_name='datausuario',
            name='aumentoTransporte',
        ),
        migrations.AddField(
            model_name='datausuario',
            name='gastoEducacion',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='datausuario',
            name='gastoEsparcimiento',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='datausuario',
            name='gastoHogar',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='datausuario',
            name='gastoIndumentaria',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='datausuario',
            name='gastoOtros',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='datausuario',
            name='gastoSalud',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='datausuario',
            name='gastoViviendaYServicios',
            field=models.FloatField(default=0),
        ),
    ]
