# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-12 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflaciometro', '0004_auto_20161212_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='datausuario',
            name='aumentoAlimentos',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='datausuario',
            name='aumentoTransporte',
            field=models.FloatField(default=0),
        ),
    ]
