# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-15 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inflaciometro', '0006_auto_20161212_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datausuario',
            name='aumentoAlimentos',
        ),
        migrations.RemoveField(
            model_name='datausuario',
            name='aumentoTransporte',
        ),
    ]
